backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use backend\services\news\NewsService;
use Yii;
use common\models\news\News;
use common\models\news\NewsSearch;
use yii\base\Module;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 *
 * @property NewsService $service
 */
class NewsController extends Controller
{
    /**
     * @var NewsService $service
     */
    protected $service;

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * NewsController constructor.
     * @param string $id
     * @param Module $module
     * @param array $config
     * @param NewsService $service
     */
    public function __construct(string $id, Module $module, array $config = [], NewsService $service)
    {
        parent::__construct($id, $module, $config);
        $this->service = $service;
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \Throwable
     */
    public function actionCreate()
    {
        $model = new News();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            try {
                $model = $this->service->create(Yii::$app->request->post());
                Yii::$app->session->setFlash('success', 'Успешно сохранено');
                return $this->redirect(['view', 'id' => $model->id]);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            try {
                $model = $this->service->update(Yii::$app->request->post());
                Yii::$app->session->setFlash('success', 'Успешно сохранено');
                return $this->redirect(['view', 'id' => $model->id]);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/NewsController.php
<?php

namespace frontend\controllers;

use frontend\services\news\NewsService;
use yii\base\Module;

/**
 * Class NewsController
 * @package frontend\controllers
 *
 * @property NewsService $newsService
 */
class NewsController extends Controller
{
    /**
     * @var NewsService $newsService
     */
    protected $newsService;

    /**
     * NewsController constructor.
     * @param string $id
     * @param Module $module
     * @param array $config
     * @param NewsService $service
     */
    public function __construct(string $id, Module $module, array $config = [], NewsService $service)
    {
        $this->newsService = $service;
        parent::__construct($id, $module, $config);
    }

    /**
     * Страница списка новостей
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', $this->newsService->getLast());
    }

    /**
     * Страница просмотра новостей
     *
     * @param string $slug
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionView(string $slug)
    {
        return $this->render('view', [
            'newsItem' => $this->newsService->getBySlug($slug),
        ]);
    }
}

frontend/views/news/index.php
<?php

use yii\helpers\Url;

/** @var \common\models\news\News[] $news */
?>

<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
            </p>
            <div class="jumbotron">
                <h1>Последние новости</h1>
            </div>
            <div class="row">
                <?php foreach ($news as $newsItem) : ?>
                    <div class="col-xs-6 col-lg-4">
                        <div class="img">
                            <img src="<?= $newsItem->getImageUrl('340x250') ?>" alt="">
                        </div>
                        <h2><?= $newsItem->title ?></h2>
                        <p><?= $newsItem->description ?></p>
                        <p><a class="btn btn-default" href="<?= Url::to(['news/view', 'slug' => $newsItem->slug]) ?>" role="button">Подробнее &raquo;</a></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-12">
            <?= \yii\widgets\LinkPager::widget([
                'pagination' => $pages,
            ]) ?>
        </div>
    </div>
</div>

frontend/views/news/view.php
<?php
/** @var \common\models\news\News $newsItem */
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1><?= $newsItem->title ?></h1>
        </div>
        <div class="col-md-12">
            <span>Добавлено: <?= $newsItem->getCreatedAt() ?></span>
        </div>
        <div class="col-md-12">
            <p><?= $newsItem->content ?></p>
        </div>
    </div>
</div>