backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use backend\forms\users\RoleForm;
use backend\forms\users\UserForm;
use backend\services\users\UsersService;
use Yii;
use common\models\users\User;
use common\models\users\UserSearch;
use yii\base\Response;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'role-save'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserForm();

        $usersService = new UsersService(new User());
        if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {
            try {
                $user = $usersService->create($model);
                Yii::$app->session->setFlash('success', 'Пользователь успешно создан');
                return $this->redirect(['view', 'id' => $user->id]);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);
        $model = new UserForm();
        $model->prepareCreate($user);

        $usersService = new UsersService($user);
        if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post())) {
            try {
                $user = $usersService->create($model);
                Yii::$app->session->setFlash('success', 'Пользователь успешно обновлен');
                return $this->redirect(['view', 'id' => $user->id]);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        //заполняем форму Ролей
        /** @var $roleForm RoleForm */
        $roleForm = new RoleForm();
        $roleForm->prepareUpdate($user);

        return $this->render('update', [
            'model' => $model,
            'roleForm' => $roleForm,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @param $id
     * @return Response
     * @throws \yii\web\HttpException
     */
    public function actionRoleSave($id)
    {
        $user = $this->findModel($id);

        /**
         * @var RoleForm $roleForm
         */
        $roleForm = new RoleForm();

        if ($roleForm->load(Yii::$app->request->post())) {

            /**
             * @var $userService UsersService
             */
            $userService = new UsersService($user);

            try {
                if ($userService->setRolesData($roleForm->attributes)) {
                    Yii::$app->session->setFlash('success', 'Успешно сохранено');
                }

            } catch (\Exception $exception) {
               Yii::$app->session->setFlash('error', $exception->getMessage());
            }

            return $this->redirect(['update', 'id' => $user->id]);
        }
    }
}

backend/views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')->dropDownList([
        \common\models\users\User::STATUS_ACTIVE => 'Активный',
        \common\models\users\User::STATUS_DELETED => 'Удален',
    ]) ?>

    <?= $form->field($model, 'username')->textInput() ?>

    <?= $form->field($model, 'email')->textInput() ?>

    <?= $form->field($model, 'password')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/_formRoles.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use nex\chosen\Chosen;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $roleForm \backend\forms\users\RoleForm */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin([
    'id' => 'form-role-update',
    'action' => Url::to(['/users/role-save', 'id' => $roleForm->id_user]),
    'options' => ['enctype' => 'multipart/form-data'],
]); ?>
<div class="box">
    <div class="box-body">
        <div class="row">
            <div class="col-sm-6">
                <?= $form->field($roleForm, 'roles')->widget(Chosen::className(), [
                    'placeholder' => 'Роли',
                    'items' => $roleForm->getRolesDataList(),
                    'multiple' => true
                ]); ?>
            </div>
            <div class="col-sm-6">
                <?= $form->field($roleForm, 'permissions')->widget(Chosen::className(), [
                    'placeholder' => 'Права',
                    'items' => $roleForm->getPermissionsDataList(),
                    'multiple' => true
                ]); ?>
            </div>
        </div>
    </div>

    <div class="box-footer text-left">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success', 'name' => 'save-button']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

backend/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\users\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\users\User */

$this->title = 'Создание пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\users\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>

    <p>
        <?= Html::a('Добавить пользователя', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= \kartik\dynagrid\DynaGrid::widget([
        'gridOptions' => [
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            [
                'attribute' => 'username',
                'label' => 'Логин',
            ],
            'email:email',
            [
                'attribute' => 'status',
                'label' => 'Статус',
            ],
            [
                'attribute' => 'created_at',
                'label' => 'Создано',
            ],
            [
                'attribute' => 'updated_at',
                'label' => 'Обновлено',
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
        'options'=>['id'=>'dynagrid-users'],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\users\User */

$this->title = 'Обновление пользователя: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновление';

$items[] = [
    'label' => 'Профиль',
    'content' => $this->render('_form', ['model' => $model]),
];

    $items[] = [
        'label' => 'Права',
        'content' => $this->render('_formRoles', ['roleForm' => $roleForm]),
    ];
?>
<?php echo \yii\bootstrap\Tabs::widget([
    'items' => $items,
    'options' => ['tag' => 'div', 'class' => ''],
    'itemOptions' => ['tag' => 'div'],
    'headerOptions' => ['class' => ''],
    'clientOptions' => ['collapsible' => false],
]);

?>

backend/views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\users\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены что хотите удалить пользователя?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>